// 世界制覇バージョン（開発中・00001のみ表示）
// 国データ・ステージ分けは、写真の教材を拡大して読み取った内容を参考にしている。
// 教材では各ステージごとに番号が①からふり直されている(例: 第3ステージは①アメリカ合衆国
// から④大西洋まで)。アプリ版はレベル10ごとに1ヵ国というシンプルな仕組みにするため、
// 4ステージ通して1〜100の連番にまとめ直した。
// trivia は下書き（第一稿）。教材に文章があれば、それを見ながら本格的に書き直す。
const WORLD_STAGES = [
  { id: 1, name: 'ユーラシアステージ', desc: '日本からヨーロッパへ（教材どおり、①〜㉘を実際に読み取って作成）' },
  { id: 2, name: 'アフリカ・アジア・オセアニアステージ', desc: 'エジプトからインド洋を越えてオセアニアへ（教材の㉙〜㊸に相当）' },
  { id: 3, name: '北アメリカステージ', desc: 'アメリカ合衆国から中米・カリブ海へ' },
  { id: 4, name: '南アメリカ・太平洋ステージ', desc: '南米から太平洋の島々へ' },
];

const WORLD_DATA = [
  // ---------- ステージ1: ユーラシア (1-28)。写真の教材を拡大して読み取った内容 ----------
  { code: 1, name: '日本', stage: 1, iso: 'jp', trivia: '世界には「自動販売機大国」というあだ名があるほど、日本には自動販売機が多い。人口約23人に1台の割合だから、道を歩けばすぐ見つかるはず！', details: { specialty: '米・魚介類', places: '富士山・京都', culture: '茶道・着物', heritage: '法隆寺・厳島神社' } },
  { code: 2, name: '大韓民国', stage: 1, iso: 'kr', trivia: '世界でもトップクラスにインターネットが速い国。おかげでeスポーツがめちゃくちゃ盛んで、プロゲーマーはスター選手みたいに人気があるんだ。', details: { specialty: 'キムチ・高麗人参', places: 'ソウル・済州島', culture: 'ハングル・韓服（ハンボク）', heritage: '昌徳宮・石窟庵' } },
  { code: 3, name: '朝鮮民主主義人民共和国', stage: 1, iso: 'kp', trivia: '首都ピョンヤンは自動車がとても少なく、道路がとても広々としている。白い制服の交通整理員が手信号で車をさばく光景も見られるよ。', details: { specialty: '鉱物資源', places: 'ピョンヤン・白頭山', culture: 'マスゲーム', heritage: '高句麗古墳群' } },
  { code: 4, name: '中華人民共和国', stage: 1, iso: 'cn', trivia: '万里の長城の全長はなんと2万kmを超える！「月から見える」というのは実は都市伝説で、本当は肉眼では見えないんだって。', details: { specialty: '茶・絹', places: '万里の長城・故宮', culture: '漢字・書道', heritage: '兵馬俑・故宮' } },
  { code: 5, name: 'モンゴル', stage: 1, iso: 'mn', trivia: '人口よりヒツジ・ヤギ・ウマなどの家畜の数の方がずっと多い！遊牧民は今でも「ゲル」という組み立て式のテントで暮らしているよ。', details: { specialty: 'カシミヤ・乳製品', places: 'ゴビ砂漠・ウランバートル', culture: '遊牧・馬頭琴', heritage: 'オルホン渓谷' } },
  { code: 6, name: 'ロシア連邦', stage: 1, iso: 'ru', trivia: '世界一面積が広い国で、なんと11のタイムゾーンをまたいでいる。東の端と西の端では、時間がまるまる1日近くズレることも！', details: { specialty: 'キャビア・毛皮', places: 'モスクワ・サンクトペテルブルク', culture: 'バレエ・マトリョーシカ', heritage: '赤の広場・エルミタージュ美術館' } },
  { code: 7, name: 'フィンランド', stage: 1, iso: 'fi', trivia: '「サンタクロースの故郷」と呼ばれる国。人口より多いくらいサウナがあると言われていて、国民のリラックス方法No.1なんだって。', details: { specialty: '木材・ベリー類', places: 'ヘルシンキ・ラップランド', culture: 'サウナ・ムーミン', heritage: 'スオメンリンナ要塞' } },
  { code: 8, name: 'スウェーデン', stage: 1, iso: 'se', trivia: '家具ブランドIKEAの発祥地。組み立て式の家具みたいに、街の名前もちょっと発音が難しいものが多いよ。', details: { specialty: '鉄鉱石・木材', places: 'ストックホルム', culture: 'フィーカ（コーヒー休憩）・IKEA', heritage: 'ドロットニングホルム宮殿' } },
  { code: 9, name: 'ノルウェー', stage: 1, iso: 'no', trivia: '夏には太陽が一日中沈まない「白夜」が見られる場所がある。逆に冬は一日中太陽が昇らない日もあるんだ。', details: { specialty: 'サーモン・石油', places: 'フィヨルド・オスロ', culture: 'バイキングの歴史', heritage: 'ヴェーガ群島' } },
  { code: 10, name: 'アイルランド', stage: 1, iso: 'ie', trivia: '妖精「レプラコーン」の伝説で有名。虹の根本には金貨の入った壺が隠されているという言い伝えがあるよ。', details: { specialty: '乳製品・ウイスキー', places: 'ダブリン・ジャイアンツコーズウェー', culture: 'ケルト音楽・妖精伝説', heritage: 'ニューグレンジ' } },
  { code: 11, name: 'イギリス', stage: 1, iso: 'gb', trivia: '世界で一番有名な時計台「ビッグベン」があるけど、実はビッグベンは時計台ではなく中の鐘の名前なんだって。', details: { specialty: '紅茶・毛織物', places: 'ロンドン・ストーンヘンジ', culture: 'サッカー・紅茶文化', heritage: 'ストーンヘンジ・ウェストミンスター宮殿' } },
  { code: 12, name: 'オランダ', stage: 1, iso: 'nl', trivia: '国土の4分の1が海抜0m以下！海に沈まないように、大昔から堤防や風車で水を管理してきたんだ。', details: { specialty: 'チューリップ・チーズ', places: 'アムステルダム・風車村', culture: '自転車文化', heritage: 'キンデルダイクの風車群' } },
  { code: 13, name: 'ベルギー', stage: 1, iso: 'be', trivia: '一人当たりのチョコレート消費量が世界トップクラス。街を歩くとチョコレート屋さんの甘い香りがあちこちで漂っているよ。', details: { specialty: 'チョコレート・ビール', places: 'ブリュッセル・ブルージュ', culture: '漫画文化', heritage: 'グランプラス' } },
  { code: 14, name: 'ドイツ', stage: 1, iso: 'de', trivia: 'ソーセージの種類はなんと1500種類以上！地域によって味も形も全然違うんだって。', details: { specialty: '自動車・ビール', places: 'ベルリン・ノイシュバンシュタイン城', culture: 'クリスマスマーケット', heritage: 'ケルン大聖堂' } },
  { code: 15, name: 'ポーランド', stage: 1, iso: 'pl', trivia: '作曲家ショパンの生まれた国。空港の名前にもショパンの名前がついているくらい、国民に愛されているよ。', details: { specialty: '琥珀・ウォッカ', places: 'ワルシャワ・クラクフ', culture: 'ショパンの音楽', heritage: 'ヴィエリチカ岩塩坑' } },
  { code: 16, name: 'チェコ', stage: 1, iso: 'cz', trivia: '首都プラハは「百塔の街」と呼ばれるほど、美しい塔がたくさん建っている絵本みたいな街だよ。', details: { specialty: 'ガラス工芸・ビール', places: 'プラハ・カルロヴィヴァリ', culture: '人形劇', heritage: 'プラハ歴史地区' } },
  { code: 17, name: 'オーストリア', stage: 1, iso: 'at', trivia: '音楽家モーツァルトの生まれ故郷。街中のいたるところで彼の顔がプリントされたチョコレートが売られているよ。', details: { specialty: 'ワイン・クリスタル', places: 'ウィーン・ザルツブルク', culture: 'クラシック音楽', heritage: 'シェーンブルン宮殿' } },
  { code: 18, name: 'フランス', stage: 1, iso: 'fr', trivia: 'エッフェル塔は建てられた当初「醜い」と大反対されたけど、今ではフランスで一番人気の観光名所になったよ。', details: { specialty: 'ワイン・チーズ', places: 'パリ・ヴェルサイユ宮殿', culture: '美食文化・ファッション', heritage: 'モンサンミッシェル' } },
  { code: 19, name: 'スイス', stage: 1, iso: 'ch', trivia: '「アルプスの少女ハイジ」の舞台。時計とチョコレートの品質は世界トップクラスで、山の空気もとってもきれいなんだ。', details: { specialty: 'チョコレート・時計', places: 'アルプス山脈・マッターホルン', culture: '酪農文化', heritage: 'ユングフラウ地域' } },
  { code: 20, name: 'ポルトガル', stage: 1, iso: 'pt', trivia: '大航海時代、世界中を旅した船乗りたちの国。名物のエッグタルトは今も世界中で愛されているよ。', details: { specialty: 'コルク・ワイン', places: 'リスボン・ポルト', culture: 'ファド（民族音楽）', heritage: 'ジェロニモス修道院' } },
  { code: 21, name: 'スペイン', stage: 1, iso: 'es', trivia: '毎年8月に「トマティーナ」というトマトを投げ合うお祭りがある。街中が真っ赤なトマトまみれになる、世界一ジューシーなお祭りだよ。', details: { specialty: 'オリーブオイル・生ハム', places: 'マドリード・バルセロナ', culture: 'フラメンコ・闘牛', heritage: 'サグラダファミリア' } },
  { code: 22, name: 'アンドラ', stage: 1, iso: 'ad', trivia: 'フランスとスペインの国境の山の中にある、とっても小さな国。スキーリゾートとして有名で、冬は雪目当ての観光客でにぎわうよ。', details: { specialty: 'タバコ・免税品', places: 'アンドララベリャ', culture: 'カタルーニャ文化の影響', heritage: 'マドリウ渓谷' } },
  { code: 23, name: 'イタリア', stage: 1, iso: 'it', trivia: 'ピザ発祥の国。実は「マルゲリータピザ」は、王妃マルゲリータのために作られたのが名前の由来なんだって。', details: { specialty: 'パスタ・オリーブオイル', places: 'ローマ・ヴェネツィア', culture: 'ルネサンス美術', heritage: 'コロッセオ・ポンペイ' } },
  { code: 24, name: 'ハンガリー', stage: 1, iso: 'hu', trivia: '首都ブダペストには天然の温泉がたくさん湧いていて、街の人たちは温泉でチェスを指しながらのんびりするのが好きなんだ。', details: { specialty: 'パプリカ・ワイン', places: 'ブダペスト', culture: '温泉文化', heritage: 'ブダペストのドナウ河岸' } },
  { code: 25, name: 'ルーマニア', stage: 1, iso: 'ro', trivia: '吸血鬼ドラキュラ伝説のモデルになった「ブラン城」がある。夜に行くとちょっぴりゾクゾクするかも！', details: { specialty: '木材・ワイン', places: 'ブカレスト・トランシルヴァニア', culture: '民族舞踊', heritage: 'ブラン城' } },
  { code: 26, name: 'ブルガリア', stage: 1, iso: 'bg', trivia: 'ヨーグルト発祥の地ともいわれている。バラの栽培も盛んで、世界のバラ油の多くはここで作られているよ。', details: { specialty: 'バラ油・ヨーグルト', places: 'ソフィア・バラの谷', culture: '民族音楽', heritage: 'リラの僧院' } },
  { code: 27, name: 'ギリシャ', stage: 1, iso: 'gr', trivia: '古代オリンピックが生まれた国。パルテノン神殿は2000年以上も前に建てられたのに、今もその姿を残しているんだ。', details: { specialty: 'オリーブ・オリーブオイル', places: 'アテネ・サントリーニ島', culture: '古代ギリシャ哲学', heritage: 'パルテノン神殿' } },
  { code: 28, name: 'ウクライナ', stage: 1, iso: 'ua', trivia: '「ヨーロッパのパンかご」と呼ばれるほど小麦の生産がさかん。国旗の色は青空と黄色いひまわり畑を表しているんだって。', details: { specialty: '小麦・ひまわり油', places: 'キーウ・オデーサ', culture: '刺繍（ヴィシヴァンカ）', heritage: 'キーウ洞窟修道院' } },

  // ---------- ステージ2: アフリカ→中東→南アジア→東南アジア→オセアニア (29-68) ----------
  // 教材は「㉙エジプトから㊸インド洋まで」と書かれており、アフリカだけでなく
  // 中東・南アジア・東南アジア・オセアニアまで続く長いステージ。
  { code: 29, name: 'エジプト', stage: 2, iso: 'eg', trivia: 'ギザの大ピラミッドは4500年以上前に作られたのに、重機もない時代にどうやって巨大な石を積んだのか、今も研究が続く大ミステリー。', details: { specialty: '綿花・ナツメヤシ', places: 'カイロ・ルクソール', culture: '古代エジプト文明', heritage: 'ピラミッド・スフィンクス' } },
  { code: 30, name: 'リビア', stage: 2, iso: 'ly', trivia: '国土のほとんどが砂漠。サハラ砂漠の一部が広がっていて、昼はとても暑いのに夜は急に冷え込むんだ。', details: { specialty: '石油・ナツメヤシ', places: 'トリポリ', culture: 'ベルベル文化', heritage: 'レプティス・マグナ遺跡' } },
  { code: 31, name: 'チュニジア', stage: 2, iso: 'tn', trivia: '古代都市カルタゴがあった場所。オリーブオイルの生産量は世界トップクラスで、まさに「オリーブの国」だよ。', details: { specialty: 'オリーブオイル・ナツメヤシ', places: 'チュニス・カルタゴ遺跡', culture: '地中海文化', heritage: 'カルタゴ遺跡' } },
  { code: 32, name: 'アルジェリア', stage: 2, iso: 'dz', trivia: 'アフリカで一番面積が広い国。国土の大部分がサハラ砂漠におおわれているよ。', details: { specialty: '天然ガス・石油', places: 'アルジェ', culture: 'ベルベル・アラブ文化', heritage: 'ティムガッド遺跡' } },
  { code: 33, name: 'モロッコ', stage: 2, iso: 'ma', trivia: '青一色に塗られた「青い街」シャウエンが有名。まるで空の中を歩いているような不思議な景色が広がるんだ。', details: { specialty: 'アルガンオイル・絨毯', places: 'マラケシュ・シャウエン', culture: 'モザイクタイル装飾', heritage: 'フェズ旧市街' } },
  { code: 34, name: 'モーリタニア', stage: 2, iso: 'mr', trivia: 'サハラ砂漠が国土の大部分を占める。鉄鉱石がたくさん採れて、世界最長級の貨物列車が鉄鉱石を運んでいるよ。', details: { specialty: '鉄鉱石・魚介類', places: 'ヌアクショット', culture: '遊牧民文化', heritage: 'ウアダン旧市街' } },
  { code: 35, name: 'マリ', stage: 2, iso: 'ml', trivia: 'かつて「トンブクトゥ」という町は、金と塩の交易で栄えた伝説の都市だった。今も歴史ある建物が残っているよ。', details: { specialty: '綿花・金', places: 'トンブクトゥ・ジェンネ', culture: '交易都市文化', heritage: 'ジェンネの旧市街' } },
  { code: 36, name: 'ニジェール', stage: 2, iso: 'ne', trivia: '国土のほとんどが砂漠だけど、ウランの産出量は世界でも有数。暑さはアフリカ屈指と言われているんだ。', details: { specialty: 'ウラン・落花生', places: 'ニアメ', culture: '遊牧民トゥアレグ文化', heritage: 'アガデスの旧市街' } },
  { code: 37, name: 'チャド', stage: 2, iso: 'td', trivia: '国名の由来にもなった「チャド湖」がある。かつては日本の面積の半分ほどもある大きな湖だったんだって。', details: { specialty: '綿花・石油', places: 'ンジャメナ・チャド湖', culture: '多民族文化', heritage: 'エネディ山地の岩絵' } },
  { code: 38, name: 'スーダン', stage: 2, iso: 'sd', trivia: '実はエジプトよりピラミッドの数が多い！「ヌビアのピラミッド」と呼ばれる古代の遺跡がたくさん残っているよ。', details: { specialty: '綿花・アラビアゴム', places: 'ハルツーム・ヌビア地方', culture: 'ヌビア文化', heritage: 'メロエの古代都市群' } },
  { code: 39, name: 'エチオピア', stage: 2, iso: 'et', trivia: 'コーヒー発祥の地と言われている。伝説によると、ヤギがコーヒーの実を食べて元気になったのがきっかけなんだとか。', details: { specialty: 'コーヒー豆・皮革', places: 'アディスアベバ・ラリベラ', culture: '独自の暦と文字', heritage: 'ラリベラの岩窟教会群' } },
  { code: 40, name: 'ケニア', stage: 2, iso: 'ke', trivia: '世界的なマラソン選手をたくさん輩出している国。標高の高い場所でのトレーニングが強さの秘密と言われているよ。', details: { specialty: '茶・コーヒー', places: 'ナイロビ・マサイマラ', culture: 'マサイ族の伝統', heritage: 'ラム旧市街' } },
  { code: 41, name: 'タンザニア', stage: 2, iso: 'tz', trivia: 'アフリカ最高峰キリマンジャロ山がある。赤道に近いのに山頂には雪が積もっているんだ。', details: { specialty: 'コーヒー・香辛料', places: 'キリマンジャロ・ザンジバル島', culture: 'スワヒリ文化', heritage: 'ンゴロンゴロ自然保護区' } },
  { code: 42, name: 'ナイジェリア', stage: 2, iso: 'ng', trivia: 'アフリカで一番人口が多い国。映画産業も盛んで、「ノリウッド」と呼ばれるほど毎年たくさんの映画が作られているよ。', details: { specialty: '石油・カカオ', places: 'ラゴス・アブジャ', culture: '映画産業「ノリウッド」', heritage: 'オスン聖なる森' } },
  { code: 43, name: 'ガーナ', stage: 2, iso: 'gh', trivia: '世界有数のカカオ豆の産地。チョコレートの原料の多くは、実はこの国からやってきているんだ。', details: { specialty: 'カカオ・金', places: 'アクラ・ケープコースト城', culture: 'ケンテ布の伝統織物', heritage: 'ケープコースト城' } },
  { code: 44, name: 'コートジボワール', stage: 2, iso: 'ci', trivia: '国名はフランス語で「象牙海岸」という意味。カカオ豆の生産量は世界一を誇っているよ。', details: { specialty: 'カカオ・コーヒー', places: 'アビジャン・ヤムスクロ', culture: '仮面舞踊', heritage: 'タイ国立公園' } },
  { code: 45, name: 'コンゴ民主共和国', stage: 2, iso: 'cd', trivia: 'アマゾンに次ぐ広さの熱帯雨林が広がっている。ゴリラなど貴重な野生動物のすみかにもなっているんだ。', details: { specialty: '銅・ダイヤモンド', places: 'キンシャサ・コンゴ川', culture: 'リンガラ音楽', heritage: 'ヴィルンガ国立公園' } },
  { code: 46, name: '南アフリカ共和国', stage: 2, iso: 'za', trivia: 'アフリカ大陸とインド洋・大西洋が出会う「喜望峰」がある。たくさんの民族が暮らすことから「レインボーネーション」とも呼ばれるよ。', details: { specialty: '金・ダイヤモンド', places: 'ケープタウン・喜望峰', culture: '多民族「レインボーネーション」', heritage: 'ロベン島' } },
  { code: 47, name: 'サウジアラビア', stage: 2, iso: 'sa', trivia: 'イスラム教で最も神聖な都市メッカがある。世界最大級の石油産出国でもあるんだ。', details: { specialty: '石油・ナツメヤシ', places: 'メッカ・リヤド', culture: 'イスラム文化の中心地', heritage: 'マダイン・サーレハ' } },
  { code: 48, name: 'イエメン', stage: 2, iso: 'ye', trivia: 'コーヒーの語源になったとも言われる港町モカがある。「モカコーヒー」の名前はここから来ているんだって。', details: { specialty: 'コーヒー・乳香', places: 'サナア旧市街', culture: '伝統的な高層建築', heritage: 'サナア旧市街' } },
  { code: 49, name: 'アラブ首長国連邦', stage: 2, iso: 'ae', trivia: '高さ828mを誇る世界一高いビル「ブルジュ・ハリファ」がある。砂漠の中に近未来都市ドバイが広がっているよ。', details: { specialty: '石油・天然ガス', places: 'ドバイ・アブダビ', culture: '急速な近代化都市文化', heritage: 'アル・アイン' } },
  { code: 50, name: 'カタール', stage: 2, iso: 'qa', trivia: '2022年にサッカーワールドカップが開催された国。天然ガスの輸出量は世界トップクラスなんだ。', details: { specialty: '天然ガス・石油', places: 'ドーハ', culture: 'サッカー文化', heritage: 'アル・ズバラ考古遺跡' } },
  { code: 51, name: 'クウェート', stage: 2, iso: 'kw', trivia: '石油の産出量が多く、街には近未来的な塔「クウェートタワー」がそびえているよ。', details: { specialty: '石油', places: 'クウェート・シティ', culture: '湾岸の商業文化', heritage: 'クウェートタワー' } },
  { code: 52, name: 'イラク', stage: 2, iso: 'iq', trivia: 'チグリス川とユーフラテス川の間に、人類最古の文明のひとつ、メソポタミア文明が栄えた場所だよ。', details: { specialty: '石油・ナツメヤシ', places: 'バグダッド・バビロン遺跡', culture: 'メソポタミア文明の系譜', heritage: 'バビロン遺跡' } },
  { code: 53, name: 'イラン', stage: 2, iso: 'ir', trivia: 'ペルシャじゅうたんの産地として有名。古代遺跡ペルセポリスは2500年以上前の宮殿の跡なんだ。', details: { specialty: 'じゅうたん・サフラン', places: 'テヘラン・ペルセポリス', culture: 'ペルシャ文化', heritage: 'ペルセポリス' } },
  { code: 54, name: 'トルコ', stage: 2, iso: 'tr', trivia: 'アジアとヨーロッパの両方にまたがる珍しい国。街ではトルコアイスを伸ばして遊ぶパフォーマンスが人気だよ。', details: { specialty: 'じゅうたん・ドライフルーツ', places: 'イスタンブール・カッパドキア', culture: '東西文化の交差点', heritage: 'カッパドキア' } },
  { code: 55, name: 'シリア', stage: 2, iso: 'sy', trivia: '古都ダマスカスは「世界最古の首都」とも呼ばれていて、なんと5000年以上前から人が住み続けているんだ。', details: { specialty: 'オリーブ・織物', places: 'ダマスカス・パルミラ遺跡', culture: 'シルクロードの交易文化', heritage: 'パルミラ遺跡' } },
  { code: 56, name: 'パキスタン', stage: 2, iso: 'pk', trivia: '世界第2位の高峰K2がそびえる国。インダス文明という古代文明がここで栄えていたよ。', details: { specialty: '綿花・米', places: 'イスラマバード・K2', culture: 'インダス文明の系譜', heritage: 'モヘンジョダロ' } },
  { code: 57, name: 'インド', stage: 2, iso: 'in', trivia: 'タージマハルは、王様が愛する妃のために作った真っ白な墓。カレーのスパイスの種類は数百種類にもなるんだって。', details: { specialty: '茶・香辛料', places: 'タージマハル・ガンジス川', culture: 'ヒンドゥー文化・映画（ボリウッド）', heritage: 'タージマハル' } },
  { code: 58, name: 'スリランカ', stage: 2, iso: 'lk', trivia: '紅茶「セイロンティー」の産地。宝石の産出でも有名で「インド洋の宝石」とも呼ばれているよ。', details: { specialty: '紅茶・宝石', places: 'キャンディ・シギリヤロック', culture: '仏教文化', heritage: 'シギリヤ' } },
  { code: 59, name: 'バングラデシュ', stage: 2, iso: 'bd', trivia: 'ガンジス川が海に注ぐ、世界最大級の三角州（デルタ）がある国。ジュート（麻）の生産も盛んなんだ。', details: { specialty: 'ジュート・茶', places: 'ダッカ・スンダルバンス', culture: 'ベンガル文化', heritage: 'バゲルハットのモスク都市' } },
  { code: 60, name: 'ミャンマー', stage: 2, iso: 'mm', trivia: '全身が金色に輝く仏塔「シュエダゴン・パゴダ」がある。ヒスイの産出量も世界トップクラスだよ。', details: { specialty: 'ヒスイ・チーク材', places: 'ヤンゴン・バガン遺跡', culture: '上座部仏教文化', heritage: 'バガン遺跡群' } },
  { code: 61, name: 'タイ', stage: 2, iso: 'th', trivia: '「微笑みの国」と呼ばれるほど、人々の笑顔が印象的。象は昔から人々の暮らしと深く関わってきた特別な動物なんだ。', details: { specialty: '米・天然ゴム', places: 'バンコク・アユタヤ', culture: '仏教文化・微笑みの国', heritage: 'アユタヤ遺跡' } },
  { code: 62, name: 'ベトナム', stage: 2, iso: 'vn', trivia: '麺料理「フォー」が有名。女性の民族衣装「アオザイ」は、体のラインに沿ったスラっとしたシルエットが特徴だよ。', details: { specialty: '米・コーヒー', places: 'ハノイ・ハロン湾', culture: 'アオザイ・水上人形劇', heritage: 'ハロン湾' } },
  { code: 63, name: 'マレーシア', stage: 2, iso: 'my', trivia: '高さ452mのペトロナスツインタワーがそびえる。パーム油の生産量は世界トップクラスなんだ。', details: { specialty: 'パーム油・天然ゴム', places: 'クアラルンプール・ペトロナスツインタワー', culture: '多民族文化', heritage: 'マラッカ海峡都市群' } },
  { code: 64, name: 'シンガポール', stage: 2, iso: 'sg', trivia: '上半身がライオン、下半身が魚の像「マーライオン」がシンボル。小さな国土に多民族・多文化が共存しているよ。', details: { specialty: '電子機器・金融', places: 'マーライオン・マリーナベイ', culture: '多民族・多言語社会', heritage: 'シンガポール植物園' } },
  { code: 65, name: 'インドネシア', stage: 2, iso: 'id', trivia: '世界最大の島国で、なんと1万7000以上の島からできている。バリ島は世界的なリゾート地としても有名だよ。', details: { specialty: 'パーム油・香辛料', places: 'ジャカルタ・バリ島', culture: '多民族・多島文化', heritage: 'ボロブドゥール遺跡' } },
  { code: 66, name: 'フィリピン', stage: 2, iso: 'ph', trivia: '7000以上の島々からなる国。マンゴーの甘さは世界一とも言われているんだ。', details: { specialty: 'バナナ・ココナッツ', places: 'マニラ・ボラカイ島', culture: 'スペイン・アメリカの影響', heritage: 'フィリピン棚田群' } },
  { code: 67, name: 'オーストラリア', stage: 2, iso: 'au', trivia: 'コアラは1日20時間近く寝ているのんびり屋さん。カンガルーは後ろ向きにジャンプできないんだって。', details: { specialty: '羊毛・鉄鉱石', places: 'シドニー・ウルル（エアーズロック）', culture: '先住民アボリジニ文化', heritage: 'グレートバリアリーフ' } },
  { code: 68, name: 'ニュージーランド', stage: 2, iso: 'nz', trivia: 'なんと人口よりヒツジの数の方が多い！ラグビー代表チームの踊り「ハカ」は世界的に有名だよ。', details: { specialty: '羊毛・乳製品', places: 'オークランド・ミルフォードサウンド', culture: '先住民マオリ文化', heritage: 'トンガリロ国立公園' } },

  // ---------- ステージ3: 北アメリカ (69-80) ----------
  { code: 69, name: 'アメリカ合衆国', stage: 3, iso: 'us', trivia: '自由の女神像は、実はフランスからアメリカへの贈り物だった。ハンバーガーは今や世界中で愛される国民食になったよ。', details: { specialty: 'とうもろこし・IT製品', places: 'ニューヨーク・グランドキャニオン', culture: '多民族文化・映画産業', heritage: '自由の女神像' } },
  { code: 70, name: 'カナダ', stage: 3, iso: 'ca', trivia: 'メープルシロップの生産量は世界一。ナイアガラの滝は轟音とともに大量の水が流れ落ちる大迫力スポットだよ。', details: { specialty: 'メープルシロップ・木材', places: 'ナイアガラの滝・ロッキー山脈', culture: '多文化主義', heritage: 'ロッキー山脈自然公園群' } },
  { code: 71, name: 'メキシコ', stage: 3, iso: 'mx', trivia: 'タコスは屋台からレストランまでどこでも食べられる国民食。古代マヤ文明のピラミッドも各地に残っているんだ。', details: { specialty: 'アボカド・とうもろこし', places: 'メキシコシティ・チチェン・イッツァ', culture: 'マヤ・アステカ文化', heritage: 'チチェン・イッツァ' } },
  { code: 72, name: 'グアテマラ', stage: 3, iso: 'gt', trivia: 'マヤ文明の大都市があったティカル遺跡がジャングルの中に眠っている。良質なコーヒー豆の産地としても有名だよ。', details: { specialty: 'コーヒー・バナナ', places: 'ティカル遺跡・アンティグア', culture: 'マヤ文化', heritage: 'ティカル国立公園' } },
  { code: 73, name: 'ホンジュラス', stage: 3, iso: 'hn', trivia: 'マヤ文明の遺跡コパンがある。バナナの輸出が盛んで、「バナナ共和国」の由来にもなった国のひとつなんだ。', details: { specialty: 'バナナ・コーヒー', places: 'コパン遺跡', culture: 'マヤ文化', heritage: 'コパン遺跡' } },
  { code: 74, name: 'ニカラグア', stage: 3, iso: 'ni', trivia: '中央アメリカ最大の湖ニカラグア湖には、なんと淡水にすむ珍しいサメがいるんだって。', details: { specialty: 'コーヒー・砂糖', places: 'ニカラグア湖・レオン', culture: '先住民と植民地文化の融合', heritage: 'レオン・ビエホ遺跡' } },
  { code: 75, name: 'コスタリカ', stage: 3, iso: 'cr', trivia: '軍隊を持たない国として知られている。国土の4分の1以上が自然保護区に指定された、生き物たちの楽園なんだ。', details: { specialty: 'コーヒー・バナナ', places: 'アレナル火山・熱帯雨林', culture: '自然保護意識の高さ', heritage: 'ココ島国立公園' } },
  { code: 76, name: 'パナマ', stage: 3, iso: 'pa', trivia: '太平洋と大西洋を結ぶパナマ運河がある。1隻の船が通過するのに約8〜10時間もかかるんだって。', details: { specialty: 'バナナ・コーヒー', places: 'パナマ運河・パナマシティ', culture: '交易の要衝文化', heritage: 'パナマ・ビエホ遺跡' } },
  { code: 77, name: 'キューバ', stage: 3, iso: 'cu', trivia: '高級葉巻の産地として世界的に有名。音楽とダンスが大好きな国民性で、街中にサルサのリズムが流れているよ。', details: { specialty: '葉巻・砂糖', places: 'ハバナ・ビニャーレス渓谷', culture: 'サルサ・ソン音楽', heritage: 'ハバナ旧市街' } },
  { code: 78, name: 'ジャマイカ', stage: 3, iso: 'jm', trivia: 'レゲエ音楽発祥の地。「ブルーマウンテン」というブランドのコーヒーは世界最高級と言われているんだ。', details: { specialty: 'コーヒー・バナナ', places: 'キングストン・ブルーマウンテン', culture: 'レゲエ音楽', heritage: 'ブルー・アンド・ジョン・クロウ山脈' } },
  { code: 79, name: 'ハイチ', stage: 3, iso: 'ht', trivia: '世界で初めて奴隷たちの独立によって生まれた黒人共和国。カリブ海に浮かぶこの島は自由の象徴でもあるよ。', details: { specialty: 'コーヒー・カカオ', places: 'ポルトープランス・シタデル要塞', culture: 'フランスとアフリカの融合文化', heritage: 'シタデル要塞' } },
  { code: 80, name: 'ドミニカ共和国', stage: 3, iso: 'do', trivia: 'メジャーリーグで活躍する野球選手をたくさん輩出している「野球大国」。カリブ海の美しいビーチリゾートとしても人気だよ。', details: { specialty: '砂糖・コーヒー', places: 'サントドミンゴ', culture: 'メレンゲ音楽・野球', heritage: 'サントドミンゴ旧市街' } },

  // ---------- ステージ4: 南アメリカ・太平洋 (81-100) ----------
  { code: 81, name: 'コロンビア', stage: 4, iso: 'co', trivia: '高品質なコーヒー豆の産地として世界的に有名。緑色の宝石エメラルドの産出量も世界トップクラスなんだ。', details: { specialty: 'コーヒー・エメラルド', places: 'ボゴタ・カルタヘナ', culture: 'サルサ・コーヒー文化', heritage: 'カルタヘナ旧市街' } },
  { code: 82, name: 'ベネズエラ', stage: 4, iso: 've', trivia: '世界一落差の大きい滝「エンジェルフォール」がある。落差はなんと979m、途中で水が霧になって消えてしまうことも！', details: { specialty: '石油・カカオ', places: 'カラカス・エンジェルフォール', culture: '美人コンテスト大国', heritage: 'カナイマ国立公園' } },
  { code: 83, name: 'エクアドル', stage: 4, iso: 'ec', trivia: '「赤道」という意味の国名どおり、赤道直下に位置している。ガラパゴス諸島には独自の進化を遂げた生き物たちがすんでいるよ。', details: { specialty: 'バナナ・カカオ', places: 'キト・ガラパゴス諸島', culture: '先住民文化', heritage: 'ガラパゴス諸島' } },
  { code: 84, name: 'ペルー', stage: 4, iso: 'pe', trivia: '空中都市マチュピチュは、山の上に築かれた謎の多い古代遺跡。アルパカのふわふわの毛は最高級の毛糸としても人気だよ。', details: { specialty: 'じゃがいも・銀', places: 'マチュピチュ・クスコ', culture: 'インカ文明の系譜', heritage: 'マチュピチュ' } },
  { code: 85, name: 'ブラジル', stage: 4, iso: 'br', trivia: 'サッカーワールドカップを5回も制した「サッカー王国」。アマゾン川は流域面積・水量ともに世界最大の川なんだ。', details: { specialty: 'コーヒー・大豆', places: 'リオデジャネイロ・アマゾン川', culture: 'サンバ・カーニバル', heritage: 'リオの丘陵と海の景観群' } },
  { code: 86, name: 'ボリビア', stage: 4, iso: 'bo', trivia: '「天空の鏡」と呼ばれるウユニ塩湖がある。雨が降ると湖面が鏡のようになり、空と大地の境目がわからなくなるよ。', details: { specialty: '銀・天然ガス', places: 'ウユニ塩湖・ラパス', culture: '先住民文化の色濃い伝統', heritage: 'ポトシ市街' } },
  { code: 87, name: 'パラグアイ', stage: 4, iso: 'py', trivia: 'ブラジル・アルゼンチンとの国境近くにイグアスの滝がある。伝統的な飲み物マテ茶をストローで回し飲みする文化があるんだ。', details: { specialty: '大豆・綿花', places: 'イグアスの滝・アスンシオン', culture: 'グアラニー語文化', heritage: 'イエズス会伝道所遺跡' } },
  { code: 88, name: 'チリ', stage: 4, iso: 'cl', trivia: '南北の長さが4300kmもある世界一細長い国。南米大陸から遠く離れたイースター島の巨大なモアイ像も、実はチリの領土なんだ。', details: { specialty: '銅・ワイン', places: 'イースター島・アタカマ砂漠', culture: 'モアイ像で有名なラパヌイ文化', heritage: 'イースター島国立公園' } },
  { code: 89, name: 'アルゼンチン', stage: 4, iso: 'ar', trivia: '情熱的なダンス「タンゴ」発祥の地。牛肉の消費量は世界トップクラスで、ステーキ店がいたるところにあるよ。', details: { specialty: '牛肉・大豆', places: 'ブエノスアイレス・パタゴニア', culture: 'タンゴ', heritage: 'イグアス国立公園' } },
  { code: 90, name: 'ウルグアイ', stage: 4, iso: 'uy', trivia: '記念すべき第1回サッカーワールドカップを開催し、優勝もした国。国土の大部分が牧場で、羊や牛がのびのび暮らしているよ。', details: { specialty: '牛肉・羊毛', places: 'モンテビデオ・コロニア・デル・サクラメント', culture: 'マテ茶文化', heritage: 'コロニア・デル・サクラメント旧市街' } },
  { code: 91, name: 'フィジー', stage: 4, iso: 'fj', trivia: '南太平洋に浮かぶ楽園の島国。ラグビーは国民的スポーツで、7人制ラグビーでは世界トップクラスの強さを誇るよ。', details: { specialty: 'サトウキビ・ヤシ油', places: 'ナンディ・ヤサワ諸島', culture: '南太平洋の伝統儀式', heritage: 'レブカ歴史的港町' } },
  { code: 92, name: 'パプアニューギニア', stage: 4, iso: 'pg', trivia: 'なんと800以上もの言語が話されている、世界でもっとも言語が多様な国のひとつなんだ。', details: { specialty: '金・天然ガス', places: 'ポートモレスビー', culture: '800以上の多言語文化', heritage: 'クックの初期農業遺跡' } },
  { code: 93, name: 'ソロモン諸島', stage: 4, iso: 'sb', trivia: '美しいサンゴ礁が広がる島国。第二次世界大戦では激しい戦いの舞台にもなった歴史を持つよ。', details: { specialty: 'ココナッツ・木材', places: 'ホニアラ', culture: 'メラネシア文化', heritage: 'イースト・レンネル' } },
  { code: 94, name: 'バヌアツ', stage: 4, iso: 'vu', trivia: 'バンジージャンプの起源とされる伝統儀式が伝わる島。活火山を間近で見られる場所もあるんだ。', details: { specialty: 'カカオ・コプラ', places: 'ポートビラ・ヤスール火山', culture: '伝統儀式ランドダイビング', heritage: 'ロイマタ酋長の地' } },
  { code: 95, name: 'サモア', stage: 4, iso: 'ws', trivia: 'ポリネシア文化の中心地のひとつ。ラグビー選手を数多く輩出することでも知られているよ。', details: { specialty: 'ココナッツ・タロイモ', places: 'アピア', culture: 'ポリネシアの伝統「ファアサモア」', heritage: '自然豊かな伝統的集落' } },
  { code: 96, name: 'トンガ', stage: 4, iso: 'to', trivia: '太平洋で最も早く日付が変わる国のひとつ。今も国王がいる王国で、独自の伝統文化を大切にしているんだ。', details: { specialty: 'カボチャ・バニラ', places: 'ヌクアロファ', culture: '太平洋で唯一残る王国文化', heritage: 'ハアモンガ・ア・マウイ遺跡' } },
  { code: 97, name: 'キリバス', stage: 4, iso: 'ki', trivia: '赤道と日付変更線がちょうど交わる場所にある国。世界で一番最初に新しい日を迎える国と言われているよ。', details: { specialty: 'コプラ・魚介類', places: 'タラワ環礁', culture: '伝統的なカヌー文化', heritage: 'フェニックス諸島保護区' } },
  { code: 98, name: 'パラオ', stage: 4, iso: 'pw', trivia: '透明度抜群の海が広がるダイビングの聖地。クラゲに毒がない不思議な湖があることでも知られているんだ。', details: { specialty: '魚介類・観光業', places: 'ロックアイランド群', culture: '海を敬う伝統文化', heritage: 'ロックアイランド群' } },
  { code: 99, name: 'マーシャル諸島', stage: 4, iso: 'mh', trivia: '美しいサンゴ礁の環礁が連なる島国。第二次世界大戦をめぐる歴史も持つ場所なんだ。', details: { specialty: 'コプラ・魚介類', places: 'マジュロ環礁・ビキニ環礁', culture: '伝統航海術', heritage: 'ビキニ環礁核実験場' } },
  { code: 100, name: 'ツバル', stage: 4, iso: 'tv', trivia: '世界で4番目に小さい国。海面上昇の影響を受けやすく、環境問題について世界に発信し続けている国でもあるよ。', details: { specialty: 'コプラ・切手収集品', places: 'フナフティ環礁', culture: '伝統的な環礁での暮らし', heritage: 'フナフティ保護区' } },
];
