// 世界制覇バージョン（開発中・00001のみ表示）
// 国データ・ステージ分けは、写真の教材を拡大して読み取った内容を参考にしている。
// 教材では各ステージごとに番号が①からふり直されている(例: 第3ステージは①アメリカ合衆国
// から④大西洋まで)。アプリ版はレベル10ごとに1ヵ国というシンプルな仕組みにするため、
// 4ステージ通して1〜100の連番にまとめ直した。各国の「ストーリー」文はまだ後で詳しく詰める。
const WORLD_STAGES = [
  { id: 1, name: 'ユーラシアステージ', desc: '日本からヨーロッパへ（教材どおり、①〜㉘を実際に読み取って作成）' },
  { id: 2, name: 'アフリカ・アジア・オセアニアステージ', desc: 'エジプトからインド洋を越えてオセアニアへ（教材の㉙〜㊸に相当）' },
  { id: 3, name: '北アメリカステージ', desc: 'アメリカ合衆国から中米・カリブ海へ' },
  { id: 4, name: '南アメリカ・太平洋ステージ', desc: '南米から太平洋の島々へ' },
];

const WORLD_DATA = [
  // ---------- ステージ1: ユーラシア (1-28)。写真の教材を拡大して読み取った内容 ----------
  { code: 1, name: '日本', stage: 1 },
  { code: 2, name: '大韓民国', stage: 1 },
  { code: 3, name: '朝鮮民主主義人民共和国', stage: 1 },
  { code: 4, name: '中華人民共和国', stage: 1 },
  { code: 5, name: 'モンゴル', stage: 1 },
  { code: 6, name: 'ロシア連邦', stage: 1 },
  { code: 7, name: 'フィンランド', stage: 1 },
  { code: 8, name: 'スウェーデン', stage: 1 },
  { code: 9, name: 'ノルウェー', stage: 1 },
  { code: 10, name: 'アイルランド', stage: 1 },
  { code: 11, name: 'イギリス', stage: 1 },
  { code: 12, name: 'オランダ', stage: 1 },
  { code: 13, name: 'ベルギー', stage: 1 },
  { code: 14, name: 'ドイツ', stage: 1 },
  { code: 15, name: 'ポーランド', stage: 1 },
  { code: 16, name: 'チェコ', stage: 1 },
  { code: 17, name: 'オーストリア', stage: 1 },
  { code: 18, name: 'フランス', stage: 1 },
  { code: 19, name: 'スイス', stage: 1 },
  { code: 20, name: 'ポルトガル', stage: 1 },
  { code: 21, name: 'スペイン', stage: 1 },
  { code: 22, name: 'アンドラ', stage: 1 },
  { code: 23, name: 'イタリア', stage: 1 },
  { code: 24, name: 'ハンガリー', stage: 1 },
  { code: 25, name: 'ルーマニア', stage: 1 },
  { code: 26, name: 'ブルガリア', stage: 1 },
  { code: 27, name: 'ギリシャ', stage: 1 },
  { code: 28, name: 'ウクライナ', stage: 1 },

  // ---------- ステージ2: アフリカ→中東→南アジア→東南アジア→オセアニア (29-68) ----------
  // 教材は「㉙エジプトから㊸インド洋まで」と書かれており、アフリカだけでなく
  // 中東・南アジア・東南アジア・オセアニアまで続く長いステージ。
  { code: 29, name: 'エジプト', stage: 2 },
  { code: 30, name: 'リビア', stage: 2 },
  { code: 31, name: 'チュニジア', stage: 2 },
  { code: 32, name: 'アルジェリア', stage: 2 },
  { code: 33, name: 'モロッコ', stage: 2 },
  { code: 34, name: 'モーリタニア', stage: 2 },
  { code: 35, name: 'マリ', stage: 2 },
  { code: 36, name: 'ニジェール', stage: 2 },
  { code: 37, name: 'チャド', stage: 2 },
  { code: 38, name: 'スーダン', stage: 2 },
  { code: 39, name: 'エチオピア', stage: 2 },
  { code: 40, name: 'ケニア', stage: 2 },
  { code: 41, name: 'タンザニア', stage: 2 },
  { code: 42, name: 'ナイジェリア', stage: 2 },
  { code: 43, name: 'ガーナ', stage: 2 },
  { code: 44, name: 'コートジボワール', stage: 2 },
  { code: 45, name: 'コンゴ民主共和国', stage: 2 },
  { code: 46, name: '南アフリカ共和国', stage: 2 },
  { code: 47, name: 'サウジアラビア', stage: 2 },
  { code: 48, name: 'イエメン', stage: 2 },
  { code: 49, name: 'アラブ首長国連邦', stage: 2 },
  { code: 50, name: 'カタール', stage: 2 },
  { code: 51, name: 'クウェート', stage: 2 },
  { code: 52, name: 'イラク', stage: 2 },
  { code: 53, name: 'イラン', stage: 2 },
  { code: 54, name: 'トルコ', stage: 2 },
  { code: 55, name: 'シリア', stage: 2 },
  { code: 56, name: 'パキスタン', stage: 2 },
  { code: 57, name: 'インド', stage: 2 },
  { code: 58, name: 'スリランカ', stage: 2 },
  { code: 59, name: 'バングラデシュ', stage: 2 },
  { code: 60, name: 'ミャンマー', stage: 2 },
  { code: 61, name: 'タイ', stage: 2 },
  { code: 62, name: 'ベトナム', stage: 2 },
  { code: 63, name: 'マレーシア', stage: 2 },
  { code: 64, name: 'シンガポール', stage: 2 },
  { code: 65, name: 'インドネシア', stage: 2 },
  { code: 66, name: 'フィリピン', stage: 2 },
  { code: 67, name: 'オーストラリア', stage: 2 },
  { code: 68, name: 'ニュージーランド', stage: 2 },

  // ---------- ステージ3: 北アメリカ (69-80) ----------
  { code: 69, name: 'アメリカ合衆国', stage: 3 },
  { code: 70, name: 'カナダ', stage: 3 },
  { code: 71, name: 'メキシコ', stage: 3 },
  { code: 72, name: 'グアテマラ', stage: 3 },
  { code: 73, name: 'ホンジュラス', stage: 3 },
  { code: 74, name: 'ニカラグア', stage: 3 },
  { code: 75, name: 'コスタリカ', stage: 3 },
  { code: 76, name: 'パナマ', stage: 3 },
  { code: 77, name: 'キューバ', stage: 3 },
  { code: 78, name: 'ジャマイカ', stage: 3 },
  { code: 79, name: 'ハイチ', stage: 3 },
  { code: 80, name: 'ドミニカ共和国', stage: 3 },

  // ---------- ステージ4: 南アメリカ・太平洋 (81-100) ----------
  { code: 81, name: 'コロンビア', stage: 4 },
  { code: 82, name: 'ベネズエラ', stage: 4 },
  { code: 83, name: 'エクアドル', stage: 4 },
  { code: 84, name: 'ペルー', stage: 4 },
  { code: 85, name: 'ブラジル', stage: 4 },
  { code: 86, name: 'ボリビア', stage: 4 },
  { code: 87, name: 'パラグアイ', stage: 4 },
  { code: 88, name: 'チリ', stage: 4 },
  { code: 89, name: 'アルゼンチン', stage: 4 },
  { code: 90, name: 'ウルグアイ', stage: 4 },
  { code: 91, name: 'フィジー', stage: 4 },
  { code: 92, name: 'パプアニューギニア', stage: 4 },
  { code: 93, name: 'ソロモン諸島', stage: 4 },
  { code: 94, name: 'バヌアツ', stage: 4 },
  { code: 95, name: 'サモア', stage: 4 },
  { code: 96, name: 'トンガ', stage: 4 },
  { code: 97, name: 'キリバス', stage: 4 },
  { code: 98, name: 'パラオ', stage: 4 },
  { code: 99, name: 'マーシャル諸島', stage: 4 },
  { code: 100, name: 'ツバル', stage: 4 },
];
