// 世界制覇バージョン（開発中・00001のみ表示）
// 国データは写真の教材を参考にした仮リストです。正式な国名リスト・ステージ分け・
// 各国のストーリー文は、教材の内容を見ながら後で詳しく詰めます。
const WORLD_STAGES = [
  { id: 1, name: 'ユーラシアステージ', desc: '日本からヨーロッパへ' },
  { id: 2, name: 'アフリカステージ', desc: 'エジプトから南アフリカへ' },
  { id: 3, name: '北アメリカステージ', desc: 'アメリカ合衆国から中米・カリブ海へ' },
  { id: 4, name: '南アメリカ・太平洋ステージ', desc: '南米から太平洋の島々へ' },
];

const WORLD_DATA = [
  // ---------- ステージ1: ユーラシア (1-28) ----------
  { code: 1, name: '日本', stage: 1 },
  { code: 2, name: '韓国', stage: 1 },
  { code: 3, name: '中国', stage: 1 },
  { code: 4, name: 'モンゴル', stage: 1 },
  { code: 5, name: 'カザフスタン', stage: 1 },
  { code: 6, name: 'ロシア', stage: 1 },
  { code: 7, name: 'ウクライナ', stage: 1 },
  { code: 8, name: 'ベラルーシ', stage: 1 },
  { code: 9, name: 'ポーランド', stage: 1 },
  { code: 10, name: 'チェコ', stage: 1 },
  { code: 11, name: 'スロバキア', stage: 1 },
  { code: 12, name: 'ハンガリー', stage: 1 },
  { code: 13, name: 'ルーマニア', stage: 1 },
  { code: 14, name: 'ブルガリア', stage: 1 },
  { code: 15, name: 'ギリシャ', stage: 1 },
  { code: 16, name: 'イタリア', stage: 1 },
  { code: 17, name: 'スイス', stage: 1 },
  { code: 18, name: 'オーストリア', stage: 1 },
  { code: 19, name: 'ドイツ', stage: 1 },
  { code: 20, name: 'デンマーク', stage: 1 },
  { code: 21, name: 'オランダ', stage: 1 },
  { code: 22, name: 'ベルギー', stage: 1 },
  { code: 23, name: 'フランス', stage: 1 },
  { code: 24, name: 'イギリス', stage: 1 },
  { code: 25, name: 'アイルランド', stage: 1 },
  { code: 26, name: 'スペイン', stage: 1 },
  { code: 27, name: 'ポルトガル', stage: 1 },
  { code: 28, name: 'ノルウェー', stage: 1 },

  // ---------- ステージ2: アフリカ (29-56) ----------
  { code: 29, name: 'エジプト', stage: 2 },
  { code: 30, name: 'リビア', stage: 2 },
  { code: 31, name: 'チュニジア', stage: 2 },
  { code: 32, name: 'アルジェリア', stage: 2 },
  { code: 33, name: 'モロッコ', stage: 2 },
  { code: 34, name: 'モーリタニア', stage: 2 },
  { code: 35, name: 'マリ', stage: 2 },
  { code: 36, name: 'ニジェール', stage: 2 },
  { code: 37, name: 'チャド', stage: 2 },
  { code: 38, name: 'スーダン', stage: 2 },
  { code: 39, name: 'エチオピア', stage: 2 },
  { code: 40, name: 'ソマリア', stage: 2 },
  { code: 41, name: 'ケニア', stage: 2 },
  { code: 42, name: 'ウガンダ', stage: 2 },
  { code: 43, name: 'タンザニア', stage: 2 },
  { code: 44, name: 'コンゴ民主共和国', stage: 2 },
  { code: 45, name: 'カメルーン', stage: 2 },
  { code: 46, name: 'ナイジェリア', stage: 2 },
  { code: 47, name: 'ガーナ', stage: 2 },
  { code: 48, name: 'コートジボワール', stage: 2 },
  { code: 49, name: 'セネガル', stage: 2 },
  { code: 50, name: 'ギニア', stage: 2 },
  { code: 51, name: 'ザンビア', stage: 2 },
  { code: 52, name: 'ジンバブエ', stage: 2 },
  { code: 53, name: 'モザンビーク', stage: 2 },
  { code: 54, name: 'アンゴラ', stage: 2 },
  { code: 55, name: 'ナミビア', stage: 2 },
  { code: 56, name: '南アフリカ共和国', stage: 2 },

  // ---------- ステージ3: 北アメリカ (57-78) ----------
  { code: 57, name: 'アメリカ合衆国', stage: 3 },
  { code: 58, name: 'カナダ', stage: 3 },
  { code: 59, name: 'メキシコ', stage: 3 },
  { code: 60, name: 'グアテマラ', stage: 3 },
  { code: 61, name: 'ベリーズ', stage: 3 },
  { code: 62, name: 'ホンジュラス', stage: 3 },
  { code: 63, name: 'エルサルバドル', stage: 3 },
  { code: 64, name: 'ニカラグア', stage: 3 },
  { code: 65, name: 'コスタリカ', stage: 3 },
  { code: 66, name: 'パナマ', stage: 3 },
  { code: 67, name: 'キューバ', stage: 3 },
  { code: 68, name: 'ジャマイカ', stage: 3 },
  { code: 69, name: 'ハイチ', stage: 3 },
  { code: 70, name: 'ドミニカ共和国', stage: 3 },
  { code: 71, name: 'バハマ', stage: 3 },
  { code: 72, name: 'トリニダード・トバゴ', stage: 3 },
  { code: 73, name: 'グレナダ', stage: 3 },
  { code: 74, name: 'セントルシア', stage: 3 },
  { code: 75, name: 'バルバドス', stage: 3 },
  { code: 76, name: 'セントクリストファー・ネイビス', stage: 3 },
  { code: 77, name: 'アンティグア・バーブーダ', stage: 3 },
  { code: 78, name: 'ドミニカ国', stage: 3 },

  // ---------- ステージ4: 南アメリカ・太平洋 (79-100) ----------
  { code: 79, name: 'コロンビア', stage: 4 },
  { code: 80, name: 'ベネズエラ', stage: 4 },
  { code: 81, name: 'ガイアナ', stage: 4 },
  { code: 82, name: 'スリナム', stage: 4 },
  { code: 83, name: 'エクアドル', stage: 4 },
  { code: 84, name: 'ペルー', stage: 4 },
  { code: 85, name: 'ブラジル', stage: 4 },
  { code: 86, name: 'ボリビア', stage: 4 },
  { code: 87, name: 'パラグアイ', stage: 4 },
  { code: 88, name: 'チリ', stage: 4 },
  { code: 89, name: 'アルゼンチン', stage: 4 },
  { code: 90, name: 'ウルグアイ', stage: 4 },
  { code: 91, name: 'オーストラリア', stage: 4 },
  { code: 92, name: 'ニュージーランド', stage: 4 },
  { code: 93, name: 'フィジー', stage: 4 },
  { code: 94, name: 'パプアニューギニア', stage: 4 },
  { code: 95, name: 'サモア', stage: 4 },
  { code: 96, name: 'トンガ', stage: 4 },
  { code: 97, name: 'バヌアツ', stage: 4 },
  { code: 98, name: 'ソロモン諸島', stage: 4 },
  { code: 99, name: 'パラオ', stage: 4 },
  { code: 100, name: 'マーシャル諸島', stage: 4 },
];
