// 世界制覇バージョン・2周目用データ(開発中・00001のみ表示)
// 1周目(world-data.js)とは別の100ヵ国。南米・オセアニア・北米カリブ海地域は
// 独立国の総数が少なく、1周目で使っていない国だけでは10〜14ヵ国そろわないため、
// その3地域のみ1周目と同じ国を一部含む(2026-08-20、先生の了承済み)。
const WORLD_STAGES_LAP2 = [
  { id: 1, name: 'ユーラシア・中央アジアステージ', desc: 'ヨーロッパの小国から、コーカサス・中央アジアへ' },
  { id: 2, name: 'アフリカ・アジアステージ', desc: '西アフリカから中央・南部アフリカ、中東・中央アジア・南アジア・東南アジアへ' },
  { id: 3, name: '中米・カリブ海ステージ', desc: '中米の国々からカリブ海の島国へ' },
  { id: 4, name: '南アメリカ・太平洋ステージ', desc: '南米の国々から太平洋の島々へ' },
];

const WORLD_DATA_LAP2 = [
  // ---------- ステージ1: ユーラシア・中央アジア (1-28) ----------
  { code: 1, name: 'アイスランド', stage: 1, region: 'europe', iso: 'is', trivia: '火山と氷河が同居する国で、地熱発電のおかげで電気のほとんどをクリーンエネルギーでまかなっている。', details: { specialty: '水産物・アルミニウム', places: 'レイキャビク・ブルーラグーン', culture: 'サガ(古い英雄物語)', heritage: 'シンクヴェトリル国立公園' } },
  { code: 2, name: 'デンマーク', stage: 1, region: 'europe', iso: 'dk', trivia: '自転車通勤がとても盛んな国で、首都コペンハーゲンには自転車専用の橋まである。', details: { specialty: '豚肉・デザイン家具', places: 'コペンハーゲン・レゴランド', culture: 'ヒュッゲ(居心地の良さ)', heritage: 'イェリング墳墓群' } },
  { code: 3, name: 'エストニア', stage: 1, region: 'europe', iso: 'ee', trivia: '国民のほとんどの行政手続きがオンラインでできる、電子国家の先進国。', details: { specialty: 'IT産業・木材', places: 'タリン旧市街', culture: '合唱の祭典', heritage: 'タリン歴史地区' } },
  { code: 4, name: 'ラトビア', stage: 1, region: 'europe', iso: 'lv', trivia: '首都リガはアールヌーヴォー建築の宝庫と呼ばれ、街全体が美術館のような雰囲気。', details: { specialty: '木材・食品加工', places: 'リガ旧市街', culture: '民謡ダイナ', heritage: 'リガ歴史地区' } },
  { code: 5, name: 'リトアニア', stage: 1, region: 'europe', iso: 'lt', trivia: 'バルト三国で一番南にある国で、バスケットボールがまるで国技のように大人気。', details: { specialty: 'レーザー技術・食品', places: 'ヴィリニュス旧市街', culture: 'バスケットボール文化', heritage: 'ヴィリニュス歴史地区' } },
  { code: 6, name: 'ベラルーシ', stage: 1, region: 'europe', iso: 'by', trivia: '国土の3分の1以上が森林におおわれていて、ヨーロッパバイソンが野生で暮らす森もある。', details: { specialty: '機械・木材', places: 'ミンスク', culture: '伝統刺繍', heritage: 'ベロヴェーシの森' } },
  { code: 7, name: 'モルドバ', stage: 1, region: 'europe', iso: 'md', trivia: '地下に広がる巨大なワイン貯蔵庫があり、そのトンネルの総延長は200kmを超える。', details: { specialty: 'ワイン・果物', places: 'キシナウ・クリコバワイナリー', culture: 'ワイン文化', heritage: 'オルヘイウル・ヴェキ' } },
  { code: 8, name: 'スロバキア', stage: 1, region: 'europe', iso: 'sk', trivia: '人口あたりの城の数が世界でもトップクラスで、「城の国」とも呼ばれる。', details: { specialty: '自動車産業', places: 'ブラチスラヴァ城', culture: '木造教会建築', heritage: 'スピシュ城' } },
  { code: 9, name: 'スロベニア', stage: 1, region: 'europe', iso: 'si', trivia: '国土の半分以上が森林で、湖の上に浮かぶ小さな島に教会が建つブレッド湖が有名。', details: { specialty: '木材・観光', places: 'ブレッド湖・リュブリャナ', culture: 'アルプス山岳文化', heritage: 'シュコツィアン鍾乳洞' } },
  { code: 10, name: 'クロアチア', stage: 1, region: 'europe', iso: 'hr', trivia: 'ネクタイ発祥の地といわれていて、もともとクロアチアの兵士の首元の布がヨーロッパに広まったんだって。', details: { specialty: '観光・造船', places: 'ドゥブロヴニク旧市街', culture: 'ネクタイ発祥の文化', heritage: 'プリトヴィツェ湖群国立公園' } },
  { code: 11, name: 'ボスニア・ヘルツェゴビナ', stage: 1, region: 'europe', iso: 'ba', trivia: '古都モスタルには16世紀に作られた美しい石橋があり、夏には橋から川へ飛び込む伝統の競技会が開かれる。', details: { specialty: '木材・金属加工', places: 'モスタル橋・サラエボ', culture: '多宗教が共存する街並み', heritage: 'モスタル旧市街の橋' } },
  { code: 12, name: 'セルビア', stage: 1, region: 'europe', iso: 'rs', trivia: '発明家ニコラ・テスラの生まれた国で、首都ベオグラードの空港は彼の名前がついている。', details: { specialty: '農業・機械', places: 'ベオグラード', culture: '民族音楽トランペット祭', heritage: 'ストゥデニツァ修道院' } },
  { code: 13, name: 'モンテネグロ', stage: 1, region: 'europe', iso: 'me', trivia: '国名は「黒い山」という意味。切り立った山と青いアドリア海の景色が観光客に大人気。', details: { specialty: '観光・アルミニウム', places: 'コトル湾', culture: '山岳民族の伝統', heritage: 'コトル自然文化・歴史地域' } },
  { code: 14, name: '北マケドニア', stage: 1, region: 'europe', iso: 'mk', trivia: 'アレクサンダー大王ゆかりの地とされ、首都スコピエには彼の巨大な像が建っている。', details: { specialty: '農業・繊維', places: 'オフリド湖', culture: '正教会の伝統', heritage: 'オフリド地域' } },
  { code: 15, name: 'アルバニア', stage: 1, region: 'europe', iso: 'al', trivia: '国旗には黒い双頭の鷲が描かれていて、国民は自分の国を「鷲の国(シュチパリア)」と呼ぶ。', details: { specialty: '観光・鉱業', places: 'ベラト旧市街', culture: '伝統多声合唱', heritage: 'ブトリント遺跡' } },
  { code: 16, name: 'マルタ', stage: 1, region: 'europe', iso: 'mt', trivia: '地中海に浮かぶとても小さな島国だけど、街全体が世界遺産の首都バレッタを持つ。', details: { specialty: '観光・金融業', places: 'バレッタ', culture: '騎士団の歴史', heritage: 'バレッタ旧市街' } },
  { code: 17, name: 'キプロス', stage: 1, region: 'europe', iso: 'cy', trivia: 'ギリシャ神話で愛と美の女神アフロディーテが生まれた島とされている。', details: { specialty: '観光・海運業', places: 'アフロディーテの岩', culture: 'ギリシャ・トルコ両方の文化', heritage: 'パフォスの考古遺跡' } },
  { code: 18, name: 'ルクセンブルク', stage: 1, region: 'europe', iso: 'lu', trivia: '国土はとても小さいのに、一人当たりの国民所得は世界トップクラス。', details: { specialty: '金融業・鉄鋼', places: 'ルクセンブルク市の旧市街', culture: '三言語(仏独ルクセンブルク語)文化', heritage: 'ルクセンブルク市街の要塞群' } },
  { code: 19, name: 'リヒテンシュタイン', stage: 1, region: 'europe', iso: 'li', trivia: 'スイスとオーストリアの間にある、面積が日本の小さな市くらいしかない小さな国。', details: { specialty: '金融業・精密機器', places: 'ファドゥーツ城', culture: '君主制の伝統', heritage: 'ファドゥーツ城下町' } },
  { code: 20, name: 'サンマリノ', stage: 1, region: 'europe', iso: 'sm', trivia: '世界最古の共和国と言われていて、建国はなんと西暦301年までさかのぼる。', details: { specialty: '観光・切手', places: 'グアイタの塔', culture: '共和制の伝統', heritage: 'サンマリノ歴史地区とティターノ山' } },
  { code: 21, name: 'モナコ', stage: 1, region: 'europe', iso: 'mc', trivia: '世界で2番目に小さい国で、毎年開かれるF1モナコグランプリは市街地を走る珍しいレース。', details: { specialty: '観光・金融業', places: 'モンテカルロ', culture: 'カジノ・レース文化', heritage: '大公宮殿' } },
  { code: 22, name: 'バチカン', stage: 1, region: 'europe', iso: 'va', trivia: '世界で一番小さい国で、面積は東京ディズニーランドよりも小さい。', details: { specialty: '出版・観光', places: 'サンピエトロ大聖堂', culture: 'カトリックの総本山', heritage: 'バチカン市国' } },
  { code: 23, name: 'ジョージア', stage: 1, region: 'europe', iso: 'ge', trivia: 'ワイン発祥の地ともいわれていて、8000年前から土の中の壺でワインを造る伝統製法が今も続いている。', details: { specialty: 'ワイン・果物', places: 'トビリシ旧市街', culture: '土壺ワイン醸造', heritage: 'ムツヘタの歴史的建造物群' } },
  { code: 24, name: 'アルメニア', stage: 1, region: 'europe', iso: 'am', trivia: '世界で最初にキリスト教を国の宗教として認めた国とされている。', details: { specialty: '農業・宝石加工', places: 'セヴァン湖', culture: '古代キリスト教建築', heritage: 'ハフパット修道院' } },
  { code: 25, name: 'アゼルバイジャン', stage: 1, region: 'europe', iso: 'az', trivia: '首都バクーには昔から地面から自然に火が噴き出す「炎の山」があり、街の愛称も「炎の国」。', details: { specialty: '石油・天然ガス', places: 'バクー旧市街', culture: '絨毯織り', heritage: 'バクー城壁都市' } },
  { code: 26, name: 'カザフスタン', stage: 1, region: 'eastasia', iso: 'kz', trivia: '世界最大の内陸国で、国土面積は日本の約7倍もある。', details: { specialty: '石油・鉱物資源', places: 'アスタナ', culture: '遊牧民の伝統', heritage: 'テュルク系遊牧民の史跡群' } },
  { code: 27, name: 'ウズベキスタン', stage: 1, region: 'eastasia', iso: 'uz', trivia: 'かつてシルクロードの中継地として栄えた古都サマルカンドがあり、青いタイルの建物が美しい。', details: { specialty: '綿花・天然ガス', places: 'サマルカンド', culture: 'シルクロード文化', heritage: 'サマルカンド旧市街' } },
  { code: 28, name: 'トルクメニスタン', stage: 1, region: 'eastasia', iso: 'tm', trivia: '砂漠のど真ん中に「地獄の門」と呼ばれる、何十年も燃え続けているガス採掘跡の穴がある。', details: { specialty: '天然ガス・綿花', places: 'ダルヴァザ(地獄の門)', culture: '遊牧民・絨毯文化', heritage: '古代メルヴ遺跡' } },

  // ---------- ステージ2: アフリカ・アジア (29-66) ----------
  { code: 29, name: 'セネガル', stage: 2, region: 'africa', iso: 'sn', trivia: 'アフリカ大陸最西端の国で、首都ダカールはかつて世界一過酷といわれたパリ・ダカールラリーのゴール地点だった。', details: { specialty: '落花生・魚介類', places: 'ゴレ島', culture: 'サッカー・レスリング人気', heritage: 'ゴレ島' } },
  { code: 30, name: 'ギニア', stage: 2, region: 'africa', iso: 'gn', trivia: 'ボーキサイト(アルミニウムの原料)の埋蔵量が世界トップクラスで、世界中のアルミ製品を支えている。', details: { specialty: 'ボーキサイト・金', places: 'コナクリ', culture: '仮面舞踊', heritage: 'ニンバ山厳正自然保護区' } },
  { code: 31, name: 'シエラレオネ', stage: 2, region: 'africa', iso: 'sl', trivia: '国名は「ライオンの山」という意味で、昔の航海者が海から見た山の形をライオンに例えたのが由来。', details: { specialty: 'ダイヤモンド・鉄鉱石', places: 'フリータウン', culture: '仮面舞踊', heritage: 'タイ国立公園' } },
  { code: 32, name: 'リベリア', stage: 2, region: 'africa', iso: 'lr', trivia: 'アフリカで最も古い共和国のひとつで、19世紀にアメリカから解放された人々が建てた国。', details: { specialty: 'ゴム・鉄鉱石', places: 'モンロビア', culture: 'アメリコ・ライベリアン文化', heritage: 'サポ国立公園' } },
  { code: 33, name: 'ブルキナファソ', stage: 2, region: 'africa', iso: 'bf', trivia: '国名は現地の言葉で「誠実な人々の国」という意味を持つ。', details: { specialty: '綿花・金', places: 'ワガドゥグー', culture: '仮面と伝統音楽の祭典', heritage: 'ロロペニの遺跡群' } },
  { code: 34, name: 'トーゴ', stage: 2, region: 'africa', iso: 'tg', trivia: '国土がとても細長い形をしていて、南北に約540kmもあるのに東西は最大でも約150kmしかない。', details: { specialty: 'リン鉱石・綿花', places: 'ロメ', culture: 'ヴォドゥン(伝統宗教)', heritage: 'コウタマコウ(バタマリバ族の土地)' } },
  { code: 35, name: 'ベナン', stage: 2, region: 'africa', iso: 'bj', trivia: '「ヴードゥー教」発祥の地とされていて、今も国民の多くが伝統宗教を大切にしている。', details: { specialty: '綿花・パーム油', places: 'ガンビエの水上集落', culture: 'ヴードゥー教の祭り', heritage: 'アボメーの王宮群' } },
  { code: 36, name: 'カメルーン', stage: 2, region: 'africa', iso: 'cm', trivia: '「アフリカの縮図」と呼ばれるほど、砂漠から熱帯雨林、山や海まで多様な自然が国内にそろっている。', details: { specialty: 'カカオ・原油', places: 'カメルーン山', culture: '多民族・多言語文化', heritage: 'サンガ川流域の3か国保護区' } },
  { code: 37, name: 'ガボン', stage: 2, region: 'africa', iso: 'ga', trivia: '国土の8割以上が熱帯雨林におおわれていて、ゴリラやゾウが暮らす自然がとても豊か。', details: { specialty: '原油・木材', places: 'ロペ国立公園', culture: '仮面彫刻', heritage: 'イヴィンド国立公園' } },
  { code: 38, name: 'コンゴ共和国', stage: 2, region: 'africa', iso: 'cg', trivia: 'コンゴ川が国の南側の国境を流れていて、水量の多さは世界でも有数。', details: { specialty: '原油・木材', places: 'コンゴ川', culture: 'サプール(おしゃれ紳士文化)', heritage: 'サンガ川流域の3か国保護区' } },
  { code: 39, name: 'アンゴラ', stage: 2, region: 'africa', iso: 'ao', trivia: '原油とダイヤモンドの産出量が多く、アフリカ有数の資源国として知られている。', details: { specialty: '原油・ダイヤモンド', places: 'カランドゥーラの滝', culture: 'ポルトガル語文化圏', heritage: 'ムランジェ山塊' } },
  { code: 40, name: 'ザンビア', stage: 2, region: 'africa', iso: 'zm', trivia: '世界三大瀑布のひとつ「ヴィクトリアの滝」の一部が国内にあり、水しぶきが雷のように轟く。', details: { specialty: '銅・観光', places: 'ヴィクトリアの滝', culture: '多民族の伝統儀式', heritage: 'ヴィクトリアの滝' } },
  { code: 41, name: 'マラウイ', stage: 2, region: 'africa', iso: 'mw', trivia: '国土の5分の1近くを占める「マラウイ湖」には、世界でもここにしかいない魚が数百種類も暮らしている。', details: { specialty: '茶・タバコ', places: 'マラウイ湖', culture: '湖畔の漁業文化', heritage: 'マラウイ湖国立公園' } },
  { code: 42, name: 'モザンビーク', stage: 2, region: 'africa', iso: 'mz', trivia: '海岸線がとても長く、美しいビーチと珊瑚礁がインド洋沿いに広がっている。', details: { specialty: 'エビ・アルミニウム', places: 'モザンビーク島', culture: 'ポルトガル語文化圏', heritage: 'モザンビーク島' } },
  { code: 43, name: 'ジンバブエ', stage: 2, region: 'africa', iso: 'zw', trivia: '国名の由来にもなった石造りの古代都市遺跡「グレート・ジンバブエ」が残っている。', details: { specialty: 'タバコ・鉱物資源', places: 'グレート・ジンバブエ遺跡', culture: 'ショナ族の彫刻文化', heritage: 'グレート・ジンバブエ遺跡' } },
  { code: 44, name: 'ボツワナ', stage: 2, region: 'africa', iso: 'bw', trivia: 'ダイヤモンドの産出でアフリカ屈指の豊かさを誇り、国土の多くが野生動物の保護区になっている。', details: { specialty: 'ダイヤモンド・観光', places: 'オカバンゴ・デルタ', culture: '野生動物保護の伝統', heritage: 'オカバンゴ・デルタ' } },
  { code: 45, name: 'ナミビア', stage: 2, region: 'africa', iso: 'na', trivia: '世界最古の砂漠といわれるナミブ砂漠があり、真っ赤な砂丘が地平線まで続く絶景が見られる。', details: { specialty: 'ダイヤモンド・ウラン', places: 'ナミブ砂漠', culture: 'ヒンバ族の伝統', heritage: 'ナミブ砂海' } },
  { code: 46, name: 'マダガスカル', stage: 2, region: 'africa', iso: 'mg', trivia: '島に住む動植物の8割以上がここにしかいない固有種で、キツネザルの仲間もたくさん暮らしている。', details: { specialty: 'バニラ・コーヒー', places: 'バオバブ並木', culture: '独自の言語マダガスカル語', heritage: 'アツィナナナの雨林群' } },
  { code: 47, name: 'ルワンダ', stage: 2, region: 'africa', iso: 'rw', trivia: '「千の丘の国」と呼ばれるほど丘が多く、首都キガリは街中がとても清潔なことで知られている。', details: { specialty: 'コーヒー・茶', places: 'ヴォルカン国立公園', culture: '伝統の踊りインタョレ', heritage: 'ニュングウェ国立公園' } },
  { code: 48, name: 'ウガンダ', stage: 2, region: 'africa', iso: 'ug', trivia: 'ナイル川の源流のひとつがあり、世界最大のヴィクトリア湖のほとりに位置している。', details: { specialty: 'コーヒー・茶', places: 'マーチソン滝国立公園', culture: '多民族の伝統王国', heritage: 'ルウェンゾリ山地国立公園' } },
  { code: 49, name: 'ソマリア', stage: 2, region: 'africa', iso: 'so', trivia: 'アフリカ大陸の中でも一番長い海岸線を持ち、「アフリカの角」と呼ばれる地形の先端にある。', details: { specialty: '家畜・バナナ', places: 'モガディシュ', culture: '遊牧民の詩の伝統', heritage: 'ラス・ハーファンの洞窟壁画' } },
  { code: 50, name: 'ジブチ', stage: 2, region: 'africa', iso: 'dj', trivia: '紅海の入り口に位置する小さな国で、世界でも有数の暑さと塩湖「アッサル湖」で知られる。', details: { specialty: '中継貿易・塩', places: 'アッサル湖', culture: '遊牧民アファル・イッサ文化', heritage: 'アッサル湖' } },
  { code: 51, name: 'エスワティニ', stage: 2, region: 'africa', iso: 'sz', trivia: 'アフリカに残る数少ない君主制の国のひとつで、毎年伝統の「葦の踊り」というお祭りが開かれる。', details: { specialty: 'サトウキビ・木材', places: 'ムババーネ', culture: '葦の踊り(ウムランガ)', heritage: 'ンゴメ渓谷' } },
  { code: 52, name: 'ヨルダン', stage: 2, region: 'middleeast', iso: 'jo', trivia: '岩の壁を彫って作られた古代都市ペトラがあり、映画のロケ地としても有名。', funnyMoment: 'AKRがペトラ遺跡の入り口「シク」の細い道で迷子になる。', details: { specialty: 'リン鉱石・観光', places: 'ペトラ遺跡・死海', culture: 'ベドウィンの伝統', heritage: 'ペトラ遺跡' } },
  { code: 53, name: 'イスラエル', stage: 2, region: 'middleeast', iso: 'il', trivia: '死海は塩分濃度がとても高く、泳がなくても体が自然に浮いてしまう不思議な海。', details: { specialty: 'ハイテク産業・農業', places: '死海・エルサレム旧市街', culture: 'ハイテク・スタートアップ文化', heritage: 'エルサレム旧市街' } },
  { code: 54, name: 'レバノン', stage: 2, region: 'middleeast', iso: 'lb', trivia: '首都ベイルートはかつて「中東のパリ」と呼ばれるほど、おしゃれで国際色豊かな街だった。', details: { specialty: 'ワイン・オリーブオイル', places: 'バールベック遺跡', culture: '地中海料理文化', heritage: 'バールベック' } },
  { code: 55, name: 'オマーン', stage: 2, region: 'middleeast', iso: 'om', trivia: '乳香の産地として古くから知られ、香り高い樹脂の交易路は世界遺産にもなっている。', details: { specialty: '原油・乳香', places: 'マスカット', culture: '乳香交易の歴史', heritage: '乳香の国の遺跡群' } },
  { code: 56, name: 'バーレーン', stage: 2, region: 'middleeast', iso: 'bh', trivia: '小さな島国で、かつては世界有数の天然真珠の産地として栄えていた。', details: { specialty: '原油・真珠', places: 'バーレーン要塞', culture: '真珠採取の伝統', heritage: 'バーレーン要塞' } },
  { code: 57, name: 'アフガニスタン', stage: 2, region: 'middleeast', iso: 'af', trivia: '「世界の屋根」と呼ばれるヒンドゥークシュ山脈が国土を貫き、高い山々に囲まれている。', details: { specialty: '果物・鉱物資源', places: 'バーミヤン渓谷', culture: 'シルクロードの交差点文化', heritage: 'バーミヤン渓谷の文化的景観' } },
  { code: 58, name: 'キルギス', stage: 2, region: 'eastasia', iso: 'kg', trivia: '国土の9割以上が山地で、「中央アジアのスイス」と呼ばれるほど美しい山岳風景が広がる。', details: { specialty: '牧畜・綿花', places: 'イシク・クル湖', culture: '遊牧民の移動式住居ユルタ', heritage: 'スライマン・トー聖山' } },
  { code: 59, name: 'タジキスタン', stage: 2, region: 'eastasia', iso: 'tj', trivia: '国土の9割以上が山地で、パミール高原は「世界の屋根」の一部として知られる。', details: { specialty: '綿花・アルミニウム', places: 'パミール高原', culture: 'ペルシャ系文化', heritage: 'サラズムの原始集落遺跡' } },
  { code: 60, name: 'ネパール', stage: 2, region: 'southasia', iso: 'np', trivia: '世界最高峰エベレストがある国で、8000m級の山が国内にいくつもそびえている。', funnyMoment: 'AKRがエベレスト登頂を目指すも、寒さでガタガタ震えて断念する。', details: { specialty: '観光・繊維', places: 'エベレスト・カトマンズ', culture: 'ヒマラヤ登山文化', heritage: 'カトマンズの谷' } },
  { code: 61, name: 'ブータン', stage: 2, region: 'southasia', iso: 'bt', trivia: '国の豊かさを「国民総幸福量(GNH)」という独自のものさしで測ることで有名な国。', details: { specialty: '水力発電・観光', places: 'タクツァン僧院', culture: '国民総幸福量の考え方', heritage: 'タクツァン僧院' } },
  { code: 62, name: 'モルディブ', stage: 2, region: 'southasia', iso: 'mv', trivia: '1200以上のサンゴ礁の島々からなる国で、平均海抜が世界で一番低い国のひとつ。', details: { specialty: '観光・漁業', places: '水上コテージのリゾート', culture: 'サンゴ礁と海の暮らし', heritage: '首都マレの旧市街' } },
  { code: 63, name: 'ラオス', stage: 2, region: 'southasia', iso: 'la', trivia: '東南アジアで唯一海に面していない内陸国で、メコン川が国土を南北に流れている。', details: { specialty: '水力発電・農業', places: 'ルアンパバーン', culture: '上座部仏教文化', heritage: 'ルアンパバーンの町' } },
  { code: 64, name: 'カンボジア', stage: 2, region: 'southasia', iso: 'kh', trivia: '世界最大級の石造寺院遺跡アンコールワットがあり、国旗にもそのシルエットが描かれている。', funnyMoment: 'AKRがアンコールワットの階段があまりに急で、途中で息切れしてしまう。', details: { specialty: '縫製業・観光', places: 'アンコールワット', culture: 'クメール文化', heritage: 'アンコール遺跡群' } },
  { code: 65, name: 'ブルネイ', stage: 2, region: 'southasia', iso: 'bn', trivia: '豊富な石油と天然ガスのおかげで、国民は税金がとても少ないことで知られている。', details: { specialty: '原油・天然ガス', places: 'オマール・アリ・サイフディエン・モスク', culture: 'イスラム王制文化', heritage: 'カンポン・アイール(水上集落)' } },
  { code: 66, name: '東ティモール', stage: 2, region: 'southasia', iso: 'tl', trivia: '21世紀に入って初めて独立が認められた、アジアでもっとも新しい国のひとつ。', details: { specialty: 'コーヒー・原油', places: 'クリスト・レイ像', culture: 'ポルトガル語とテトゥン語の文化', heritage: 'ニノ・コニス・サンタナ国立公園' } },

  // ---------- ステージ3: 中米・カリブ海 (67-80) ----------
  { code: 67, name: 'ベリーズ', stage: 3, region: 'northamerica', iso: 'bz', trivia: '中米で唯一、公用語が英語の国。沖合には世界第2位の長さを誇るサンゴ礁が広がる。', details: { specialty: '砂糖・観光', places: 'グレートブルーホール', culture: '英語圏カリブ文化', heritage: 'ベリーズ珊瑚礁保護区' } },
  { code: 68, name: 'エルサルバドル', stage: 3, region: 'northamerica', iso: 'sv', trivia: '中米で一番面積が小さい国だけど、火山がたくさんあり「火山の国」とも呼ばれる。', details: { specialty: 'コーヒー・砂糖', places: 'サンタ・アナ火山', culture: 'マヤ文明の遺跡', heritage: 'ホヤ・デ・セレン遺跡' } },
  { code: 69, name: 'バハマ', stage: 3, region: 'northamerica', iso: 'bs', trivia: '700以上の島からなる国で、透明度が世界トップクラスの海が広がっている。', details: { specialty: '観光・金融業', places: 'ピンクサンドビーチ', culture: 'ジャンカヌー祭り', heritage: 'ナッソーの歴史地区' } },
  { code: 70, name: 'バルバドス', stage: 3, region: 'northamerica', iso: 'bb', trivia: '歌手リアーナの出身国として有名で、カリブ海の中でもラム酒発祥の地といわれている。', details: { specialty: 'ラム酒・観光', places: 'ブリッジタウン', culture: 'カリプソ音楽', heritage: 'ブリッジタウンの歴史地区' } },
  { code: 71, name: 'トリニダード・トバゴ', stage: 3, region: 'northamerica', iso: 'tt', trivia: '打楽器「スティールパン」発祥の国で、毎年盛大なカーニバルが開かれる。', details: { specialty: '原油・天然ガス', places: 'ピッチレイク(天然アスファルト湖)', culture: 'スティールパン音楽', heritage: 'ピッチレイク' } },
  { code: 72, name: 'アンティグア・バーブーダ', stage: 3, region: 'northamerica', iso: 'ag', trivia: '「1年に365のビーチがある」といわれるほど、たくさんの美しい海岸線を持つ島国。', details: { specialty: '観光・金融業', places: 'ネルソンズ・ドックヤード', culture: 'ヨットレース文化', heritage: 'アンティグアの海軍造船所' } },
  { code: 73, name: 'ドミニカ国', stage: 3, region: 'northamerica', iso: 'dm', trivia: '火山と温泉が多く「カリブ海の自然の島」と呼ばれるほど、豊かな熱帯雨林が広がる。', details: { specialty: 'バナナ・観光', places: 'ボイリング・レイク(沸騰する湖)', culture: '先住民カリナゴの文化', heritage: 'モーン・トロワ・ピトン国立公園' } },
  { code: 74, name: 'グレナダ', stage: 3, region: 'northamerica', iso: 'gd', trivia: 'ナツメグの生産量が世界有数で、「スパイスの島」という愛称を持つ。', details: { specialty: 'ナツメグ・観光', places: 'グランド・アンス・ビーチ', culture: 'スパイス農園文化', heritage: '水中彫刻公園' } },
  { code: 75, name: 'セントクリストファー・ネビス', stage: 3, region: 'northamerica', iso: 'kn', trivia: '面積・人口ともに南北アメリカ大陸でいちばん小さい独立国。', details: { specialty: '観光・金融業', places: 'ブリムストーンヒル要塞', culture: 'カーニバル文化', heritage: 'ブリムストーンヒル要塞国立公園' } },
  { code: 76, name: 'セントルシア', stage: 3, region: 'northamerica', iso: 'lc', trivia: '海からそびえ立つ2つの尖った火山「ピトンズ」が島のシンボルになっている。', details: { specialty: 'バナナ・観光', places: 'ピトンズ(双子火山)', culture: 'フランス・アフリカ混合文化', heritage: 'ピトン管理地域' } },
  { code: 77, name: 'セントビンセント・グレナディーン', stage: 3, region: 'northamerica', iso: 'vc', trivia: '大小合わせて32もの島々からなる国で、映画のロケ地にも使われた美しい海が広がる。', details: { specialty: 'バナナ・観光', places: 'トバゴ・ケイズ', culture: 'カリブ海の帆船文化', heritage: 'ラ・スフリエール火山' } },
  { code: 78, name: 'メキシコ', stage: 3, region: 'northamerica', iso: 'mx', trivia: '「死者の日」というカラフルなお祭りで亡くなった家族を明るく迎える、独特のお祝い文化を持つ国。', funnyMoment: 'AKRが激辛サルサソースを気合いで完食し、顔が真っ赤になる。', details: { specialty: 'トウモロコシ・原油', places: 'チチェン・イッツァ', culture: '死者の日・マリアッチ', heritage: 'テオティワカン' } },
  { code: 79, name: 'キューバ', stage: 3, region: 'northamerica', iso: 'cu', trivia: 'クラシックカーが今も現役で街を走る国として有名で、葉巻とサルサ音楽の本場でもある。', details: { specialty: '葉巻・砂糖', places: 'ハバナ旧市街', culture: 'サルサ・クラシックカー文化', heritage: 'ハバナ旧市街' } },
  { code: 80, name: 'パナマ', stage: 3, region: 'northamerica', iso: 'pa', trivia: '太平洋と大西洋を結ぶパナマ運河があり、世界中の船がこの国を通り抜けていく。', details: { specialty: '中継貿易・バナナ', places: 'パナマ運河', culture: '多民族の交易文化', heritage: 'パナマ旧市街の歴史地区' } },

  // ---------- ステージ4: 南アメリカ・太平洋 (81-100) ----------
  { code: 81, name: 'ガイアナ', stage: 4, region: 'southamerica', iso: 'gy', trivia: '南米にありながら公用語は英語で、世界最大級の一枚岩「ロライマ山」が国内にある。', details: { specialty: '砂糖・金', places: 'カイエトゥール滝', culture: '多民族(先住民・インド系)文化', heritage: 'カイエトゥール国立公園' } },
  { code: 82, name: 'スリナム', stage: 4, region: 'southamerica', iso: 'sr', trivia: '国土の9割以上が熱帯雨林におおわれていて、南米で一番小さい独立国。', details: { specialty: 'ボーキサイト・米', places: 'パラマリボ旧市街', culture: 'オランダ語圏の多民族文化', heritage: '中央スリナム自然保護区' } },
  { code: 83, name: 'コロンビア', stage: 4, region: 'southamerica', iso: 'co', trivia: 'コーヒーの生産量が世界トップクラスで、山あいの農園では今も丁寧な手摘みが行われている。', details: { specialty: 'コーヒー・花き', places: 'カルタヘナ旧市街', culture: 'サルサ・クンビア音楽', heritage: 'カルタヘナ港と要塞群' } },
  { code: 84, name: 'ベネズエラ', stage: 4, region: 'southamerica', iso: 've', trivia: '落差979mで世界一の落差を誇る「エンジェルフォール」がある国。', details: { specialty: '原油・鉄鉱石', places: 'エンジェルフォール', culture: 'ミスコンテスト文化', heritage: 'カナイマ国立公園' } },
  { code: 85, name: 'エクアドル', stage: 4, region: 'southamerica', iso: 'ec', trivia: '国名はスペイン語で「赤道」という意味で、実際に赤道線がまっすぐ国土を貫いている。', details: { specialty: 'バナナ・原油', places: 'ガラパゴス諸島', culture: '先住民ケチュア文化', heritage: 'ガラパゴス諸島' } },
  { code: 86, name: 'ペルー', stage: 4, region: 'southamerica', iso: 'pe', trivia: '空の写真でしか全体が分からない古代の巨大地上絵「ナスカの地上絵」がある。', funnyMoment: 'AKRがマチュピチュへの山道を登りきれず、途中でへたり込む。', details: { specialty: '銅・魚介類', places: 'マチュピチュ', culture: 'インカ文明の遺産', heritage: 'マチュピチュの歴史保護区' } },
  { code: 87, name: 'ブラジル', stage: 4, region: 'southamerica', iso: 'br', trivia: 'サッカーワールドカップの優勝回数が世界一多い国で、リオのカーニバルは世界最大級のお祭り。', funnyMoment: 'AKRがサンバのリズムに合わせて踊ろうとするも、リズム音痴で足がもつれる。', details: { specialty: 'コーヒー・大豆', places: 'アマゾン熱帯雨林・リオデジャネイロ', culture: 'サンバ・カーニバル', heritage: 'イグアス国立公園' } },
  { code: 88, name: 'ボリビア', stage: 4, region: 'southamerica', iso: 'bo', trivia: '雨季になると鏡のように空を映す「ウユニ塩湖」があり、世界一の絶景として有名。', details: { specialty: '天然ガス・すず', places: 'ウユニ塩湖', culture: 'アイマラ・ケチュア文化', heritage: 'ポトシ市街' } },
  { code: 89, name: 'パラグアイ', stage: 4, region: 'southamerica', iso: 'py', trivia: '南米で数少ない内陸国で、公用語としてスペイン語と先住民の言葉グアラニー語が両方使われている。', details: { specialty: '大豆・牛肉', places: 'イタイプダム', culture: 'グアラニー語バイリンガル文化', heritage: 'ラ・サンティシマ・トリニダー・デ・パラナ' } },
  { code: 90, name: 'チリ', stage: 4, region: 'southamerica', iso: 'cl', trivia: '国土が南北に約4300kmもある、世界一細長い国。北は砂漠、南は氷河という全く違う景色が広がる。', details: { specialty: '銅・ワイン', places: 'アタカマ砂漠', culture: 'モアイ像の文化(イースター島)', heritage: 'ラパ・ヌイ国立公園' } },
  { code: 91, name: 'ミクロネシア連邦', stage: 4, region: 'pacific', iso: 'fm', trivia: '607もの島々からなる太平洋の国で、海底に沈んだ巨大な石のお金「フェイ」の遺跡でも知られる。', details: { specialty: '漁業・観光', places: 'ナン・マドール遺跡', culture: '石のお金(フェイ)の伝統', heritage: 'ナン・マドール(東ミクロネシアの儀式的中心地)' } },
  { code: 92, name: 'ナウル', stage: 4, region: 'pacific', iso: 'nr', trivia: '世界で3番目に小さい国で、一周してもたった20kmほどしかない小さな島国。', details: { specialty: 'リン鉱石(かつて)', places: 'コマンドリッジ', culture: '太平洋島しょ国の文化', heritage: 'ナウルの鉱山跡地' } },
  { code: 93, name: 'フィジー', stage: 4, region: 'pacific', iso: 'fj', trivia: '「世界で一番最初に朝を迎える国」といわれることがあるほど、日付変更線のすぐ近くにある。', details: { specialty: '観光・砂糖', places: 'マナ島', culture: 'カヴァ(伝統飲料)の儀式', heritage: 'レブカ歴史的港町' } },
  { code: 94, name: 'パプアニューギニア', stage: 4, region: 'pacific', iso: 'pg', trivia: '800以上もの言語が話されている国で、世界でもっとも言語の種類が多い国のひとつ。', details: { specialty: '金・天然ガス', places: 'セピック川', culture: '多部族の仮面文化', heritage: 'クックの初期農業遺跡' } },
  { code: 95, name: 'ソロモン諸島', stage: 4, region: 'pacific', iso: 'sb', trivia: '第二次世界大戦の激戦地ガダルカナル島がある国で、美しい珊瑚礁が今も広がっている。', details: { specialty: '木材・漁業', places: 'ガダルカナル島', culture: '伝統の貝貨(貝のお金)', heritage: 'イースト・レンネル' } },
  { code: 96, name: 'バヌアツ', stage: 4, region: 'pacific', iso: 'vu', trivia: '「世界一幸福な国」に選ばれたこともある島国で、活火山への冒険ツアーが人気。', details: { specialty: '観光・コプラ', places: 'ヤスール火山', culture: 'ランドダイビング(バンジージャンプの起源)', heritage: 'チーフ・ロイ・マタ' } },
  { code: 97, name: 'サモア', stage: 4, region: 'pacific', iso: 'ws', trivia: '2011年12月30日を国全体でまるごと1日飛ばして、日付変更線をまたぎ直したユニークな歴史を持つ。', details: { specialty: '観光・農業', places: 'トスア・オーシャン・トレンチ', culture: 'ファアサモア(サモアの伝統的な生き方)', heritage: '首長制度と伝統儀礼' } },
  { code: 98, name: 'トンガ', stage: 4, region: 'pacific', iso: 'to', trivia: '太平洋で唯一、外国に植民地支配されたことがない王国として知られている。', details: { specialty: '農業・漁業', places: '王宮のあるヌクアロファ', culture: '王制の伝統儀礼', heritage: 'ハアモンガ・ア・マウイ' } },
  { code: 99, name: 'キリバス', stage: 4, region: 'pacific', iso: 'ki', trivia: '33の島が東西に広がり、地球上で最初に新しい年を迎える国として知られている。', details: { specialty: '漁業・コプラ', places: 'クリスマス島(キリティマティ)', culture: '伝統のカヌー航海術', heritage: 'フェニックス諸島保護区' } },
  { code: 100, name: 'パラオ', stage: 4, region: 'pacific', iso: 'pw', trivia: '無数の緑の島々が浮かぶ「ロックアイランド」が有名で、世界屈指の透明度を誇るダイビングスポット。', details: { specialty: '観光・漁業', places: 'ロックアイランド', culture: '海の民の伝統', heritage: 'ロックアイランドの南部の干潟' } },
];
